Driver working in test mode

diff --git a/visa b/visa
--- a/visa
+++ b/visa
@@ -1,13 +1,15 @@
 #!/bin/bash
 
-echo "DEBUG:email backend call arguments $@" 1>&2
+echo "DEBUG:visaprint backend call arguments $@" 1>&2
 
 # when called without any arguments CUPS expects us to print a backend
 # info for use in the new printer page
 if [ $# -eq 0 ]; then
-    echo "VISA Printer"
+    echo "virtual visa \"Unknown\" \"VISA Printer\""
     exit 0
 fi
+
+JOBID=$1
 
 if [ $# -eq 6 ]; then
     EPSFILE=$6
@@ -25,6 +27,17 @@ EPSTOPDF_RC=$?
 if [ $EPSTOPDF_RC -ne 0 ]; then
     echo "ERROR:Converting to PDF failed: $EPSTOPDF_STATUS" 1>&2
     exit $EPSTOPDF_RC
+fi
+
+chmod a+r $PDFFILE
+
+
+VISA_PRINT_STATUS=$(curl -X POST -H "x-auth-token: ABCDEF123456789" http://localhost:8091/api/printer --data-urlencode "jobId=$JOBID" --data-urlencode "path=$PDFFILE")
+VISA_PRINT_RC=$?
+
+if [ $EPSTOVISA_PRINT_RCPDF_RC -ne 0 ]; then
+    echo "ERROR:Sending PDF to VISA client failed: $VISA_PRINT_STATUS" 1>&2
+    exit $VISA_PRINT_RC
 fi
 
 rm -f $PDFFILE
