Use cloud instance ID as the auth token

diff --git a/visa b/visa
--- a/visa
+++ b/visa
@@ -1,7 +1,5 @@
 #!/bin/bash
 
-echo "DEBUG:visaprint backend call arguments $@" 1>&2
-
 # when called without any arguments CUPS expects us to print a backend
 # info for use in the new printer page
 if [ $# -eq 0 ]; then
@@ -10,6 +8,13 @@ if [ $# -eq 0 ]; then
 fi
 
 JOBID=$1
+
+CLOUD_INSTANCE_ID=`cloud-init query ds.meta_data.instance-id`
+
+if [ -z "$CLOUD_INSTANCE_ID" ]; then
+    echo "ERROR:Failed to get CLOUD_INSTANCE_ID from OpenStack instance metadata"
+    exit 1
+fi
 
 if [ $# -eq 6 ]; then
     EPSFILE=$6
@@ -31,11 +36,9 @@ fi
 
 chmod a+r $PDFFILE
 
+VISA_PRINT_STATUS=$(curl -X POST -H "x-auth-token: $CLOUD_INSTANCE_ID" http://localhost:8091/api/printer --data-urlencode "jobId=$JOBID" --data-urlencode "path=$PDFFILE")
 
-VISA_PRINT_STATUS=$(curl -X POST -H "x-auth-token: ABCDEF123456789" http://localhost:8091/api/printer --data-urlencode "jobId=$JOBID" --data-urlencode "path=$PDFFILE")
-VISA_PRINT_RC=$?
-
-if [ $EPSTOVISA_PRINT_RCPDF_RC -ne 0 ]; then
+if [[ $VISA_PRINT_STATUS != "ok" ]]; then
     echo "ERROR:Sending PDF to VISA client failed: $VISA_PRINT_STATUS" 1>&2
     exit $VISA_PRINT_RC
 fi
